# Generated by Django 4.2.20 on 2025-03-12 00:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil_Terapeuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(blank=True, max_length=255, null=True, verbose_name='Especialidad')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nombre de Usuario')),
            ],
            options={
                'verbose_name_plural': 'Perfiles de Terapeutas',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(blank=True, choices=[('PACIENTE', 'Paciente'), ('TERAPEUTA', 'Terapeuta')], max_length=120, null=True, verbose_name='Tipo de usuario')),
                ('representante_legal_nombre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del Representante')),
                ('representante_legal_apellido', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del Representante')),
                ('nombre_factura', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de la factura')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(default='+593', max_length=128, region=None, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe estar en formato internacional. Ejemplo: +593XXXXXXXXX.', regex='^\\+?593?\\d{9,15}$')], verbose_name='Teléfon de contacto')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Drección')),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/', verbose_name='Foto de Paciente')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento paciente')),
                ('Paciente_nombre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del Representante')),
                ('unidad_educativa', models.CharField(blank=True, max_length=255, null=True, verbose_name='Unidad educativa del paciente')),
                ('ruc', models.CharField(blank=True, help_text='C.I del Paciente', max_length=13, null=True, verbose_name='RUC / C.I')),
                ('curso', models.CharField(blank=True, max_length=255, null=True, verbose_name='curso o Paralelo')),
                ('nacionalidad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nacionalidad del Paciente')),
                ('sexo', models.CharField(blank=True, choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino')], max_length=120, null=True, verbose_name='Sexo del Paciente')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nombre de Usuario')),
                ('user_terapeuta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil_terapeuta', verbose_name='Terapeuta Asignado')),
            ],
            options={
                'verbose_name_plural': 'Perfiles de Usuario',
                'ordering': ['user'],
            },
        ),
    ]
