# Generated by Django 4.2.20 on 2025-03-12 11:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('informacion_basica', ckeditor.fields.RichTextField()),
                ('bloque_1', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('bloque_2', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('bloque_3', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('bloque_4', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('bloque_5', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('link_soporte_tecnico', models.URLField()),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='content',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='title',
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento del paciente'),
        ),
    ]
