# Generated by Django 4.2.20 on 2025-03-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_edificio_alter_profile_user_terapeuta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Paciente_nombre',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nacionalidad',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='unidad_educativa',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_terapeuta',
        ),
        migrations.AddField(
            model_name='profile',
            name='qr_code',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='qr_codes/', verbose_name='Código QR'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/%d/', verbose_name='Foto de Usuario'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='representante_legal_apellido',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Apellido del Representante'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ruc',
            field=models.CharField(blank=True, help_text='R.U.C o C.I del Representante', max_length=13, null=True, verbose_name='RUC / C.I'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de contacto'),
        ),
    ]
