# Generated by Django 4.2.20 on 2025-03-23 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_profile_paciente_nombre_remove_profile_curso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='qr_code',
        ),
    ]
