# Generated by Django 4.2.20 on 2025-04-06 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ('-valid_to',), 'verbose_name': 'Descuento', 'verbose_name_plural': 'Descuentos'},
        ),
    ]
