# Generated by Django 4.2.20 on 2025-04-06 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'verbose_name': 'Orden de Compras', 'verbose_name_plural': 'Ordenes de Compras'},
        ),
    ]
