# Generated by Django 4.2.20 on 2025-04-06 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Catálogo de Productos - Categoría', 'verbose_name_plural': 'Catálogo de Productos - Categorías'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'Catálogo de Productos - Item', 'verbose_name_plural': 'Catálogo de Productos - Items'},
        ),
    ]
