# Generated by Django 4.2.20 on 2025-04-06 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_options_alter_product_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_translation_key_locale_shop_product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='product',
            name='translation_key',
        ),
    ]
